name: Build and Deploy to S3
on:
  push:
    branches:
      - master
env:
  S3_BUCKET: teamsantos-static-websites
  BUILD_DIR: dist
jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository_owner }}/static-web-deploy:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install Node deps
        run: npm ci
      
      - name: Build site
        run: npm run build
      
      - name: Get version from package.json
        id: get_version
        run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: Upload versioned build to S3
        run: |
          aws s3 sync $BUILD_DIR s3://$S3_BUCKET/v.${{ steps.get_version.outputs.version }}/ \
            --delete \
            --cache-control "public, max-age=31536000" \
            --exclude "*.html"
          
          aws s3 sync $BUILD_DIR s3://$S3_BUCKET/v.${{ steps.get_version.outputs.version }}/ \
            --delete \
            --cache-control "no-cache, no-store, must-revalidate" \
            --content-type "text/html" \
            --include "*.html"
      
      - name: Upload to 'default' (latest)
        run: |
          aws s3 sync $BUILD_DIR s3://$S3_BUCKET/default/ \
            --delete \
            --cache-control "public, max-age=31536000" \
            --exclude "*.html"
          
          aws s3 sync $BUILD_DIR s3://$S3_BUCKET/default/ \
            --delete \
            --cache-control "no-cache, no-store, must-revalidate" \
            --content-type "text/html" \
            --include "*.html"
