name: Deploy Templates
on:
  push:
    branches: [master]
    paths:
        - 'templates/**'
  workflow_dispatch:
    inputs:
      force_deploy_all:
        description: 'Force deploy all templates'
        required: false
        default: 'false'

env:
  S3_BUCKET: teamsantos-static-websites

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      templates: ${{ steps.changed.outputs.tempates }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch full history

      - id: changed
        run: |
          echo "Checking for changed templates..."
          echo "Before commit: ${{ github.event.before }}"
          echo "Current commit: ${{ github.sha }}"
          
          # Check if this is a manual dispatch with force deploy
          if [ "${{ github.event.inputs.force_deploy_all }}" == "true" ]; then
            echo "Force deploy all templates requested"
            CHANGED=$(find templates -maxdepth 1 -mindepth 1 -type d 2>/dev/null | cut -d/ -f2 | sort -u || echo "")
          elif [ "${{ github.event.before }}" == "0000000000000000000000000000000000000000" ]; then
            # First push or new branch - check all templates folders
            echo "First push detected, checking all templates"
            CHANGED=$(find templates -maxdepth 1 -mindepth 1 -type d 2>/dev/null | cut -d/ -f2 | sort -u || echo "")
          else
            # Check if both commits exist
            if git cat-file -e "${{ github.event.before }}" 2>/dev/null && git cat-file -e "${{ github.sha }}" 2>/dev/null; then
              echo "Both commits found, doing normal diff"
              CHANGED=$(git diff --name-only "${{ github.event.before }}" "${{ github.sha }}" 2>/dev/null \
                | grep '^templates/' | cut -d/ -f2 | sort -u || echo "")
            else
              echo "One or both commits not found, trying fallback methods..."
              # Try HEAD~1 comparison
              if git cat-file -e "HEAD~1" 2>/dev/null; then
                echo "Using HEAD~1 comparison"
                CHANGED=$(git diff --name-only HEAD~1 HEAD 2>/dev/null \
                  | grep '^templates/' | cut -d/ -f2 | sort -u || echo "")
              else
                # Last resort - deploy all templates
                echo "Cannot determine changes, deploying all templates"
                CHANGED=$(find templates -maxdepth 1 -mindepth 1 -type d 2>/dev/null | cut -d/ -f2 | sort -u || echo "")
              fi
            fi
          fi
          
          # If still no changes detected, force deploy all as fallback
          if [ -z "$CHANGED" ]; then
            echo "No changes detected, falling back to deploy all templates"
            CHANGED=$(find templates -maxdepth 1 -mindepth 1 -type d 2>/dev/null | cut -d/ -f2 | sort -u || echo "")
          fi
          
          # Convert to space-separated string for output
          CHANGED_STR=$(echo "$CHANGED" | tr '\n' ' ' | sed 's/[[:space:]]*$//')
          echo "Changed templates: $CHANGED_STR"
          echo "templates=$CHANGED_STR" >> $GITHUB_OUTPUT

  deploy:
    needs: detect-changes
    if: needs.detect-changes.outputs.templates != ''
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name == 'master' && 'production' || 'staging' }}
    container:
      image: ghcr.io/${{ github.repository_owner }}/static-websites:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: npm ci

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Set to us-east-1 for CloudFront certificates

      - name: Install infra dependencies
        working-directory: infra
        run: |
          echo "Installing infra dependencies..."
          # Handle lock file sync issues
          if ! npm ci 2>/dev/null; then
            echo "npm ci failed, falling back to npm install..."
            rm -rf node_modules package-lock.json
            npm install
          fi
          echo "✅ Infra dependencies installed"

      - name: Install CDK CLI globally
        run: |
          echo "Installing CDK CLI globally..."
          npm install -g aws-cdk typescript ts-node
          echo "✅ CDK CLI installed"

      - name: Check if CDK bootstrap is needed
        id: check-bootstrap
        working-directory: infra
        shell: bash
        run: |
          echo "Checking CDK bootstrap status..."
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          
          # Function to check if region is bootstrapped
          check_bootstrap() {
            local region=$1
            echo "Checking bootstrap for region: $region"
            
            if aws cloudformation describe-stacks \
              --region "$region" \
              --stack-name CDKToolkit \
              --query 'Stacks[0].StackStatus' \
              --output text 2>/dev/null | grep -q "COMPLETE"; then
              echo "✅ Region $region is already bootstrapped"
              return 0
            else
              echo "❌ Region $region needs bootstrapping"
              return 1
            fi
          }
          
          # Check required regions
          BOOTSTRAP_NEEDED=""
          
          # Check us-east-1 (required for CloudFront certificates)
          if ! check_bootstrap "us-east-1"; then
            BOOTSTRAP_NEEDED="$BOOTSTRAP_NEEDED us-east-1"
          fi
          
          # Check eu-south-2 (your S3 bucket region - optional but recommended)
          if ! check_bootstrap "eu-south-2"; then
            BOOTSTRAP_NEEDED="$BOOTSTRAP_NEEDED eu-south-2"
          fi
          
          # Clean up and set output
          BOOTSTRAP_NEEDED=$(echo "$BOOTSTRAP_NEEDED" | xargs)
          echo "bootstrap-needed=$BOOTSTRAP_NEEDED" >> $GITHUB_OUTPUT
          echo "account-id=$ACCOUNT_ID" >> $GITHUB_OUTPUT
          
          if [ -n "$BOOTSTRAP_NEEDED" ]; then
            echo "🔄 Bootstrap needed for regions: $BOOTSTRAP_NEEDED"
          else
            echo "✅ All regions are already bootstrapped"
          fi

      - name: Bootstrap CDK regions
        if: steps.check-bootstrap.outputs.bootstrap-needed != ''
        working-directory: infra
        shell: bash
        run: |
          echo "Bootstrapping CDK for regions: ${{ steps.check-bootstrap.outputs.bootstrap-needed }}"
          ACCOUNT_ID="${{ steps.check-bootstrap.outputs.account-id }}"
          
          for region in ${{ steps.check-bootstrap.outputs.bootstrap-needed }}; do
            echo "🔄 Bootstrapping region: $region"
            CDK_DEFAULT_ACCOUNT=$ACCOUNT_ID CDK_DEFAULT_REGION=$region \
            npx cdk bootstrap "aws://$ACCOUNT_ID/$region" \
              --require-approval never \
              --verbose \
              -c "templates=dummy"
            
            # Verify bootstrap was successful
            if aws cloudformation describe-stacks \
              --region "$region" \
              --stack-name CDKToolkit \
              --query 'Stacks[0].StackStatus' \
              --output text 2>/dev/null | grep -q "COMPLETE"; then
              echo "✅ Successfully bootstrapped $region"
            else
              echo "❌ Failed to bootstrap $region"
              exit 1
            fi
          done

      - name: Build CDK template
        working-directory: infra
        run: |
          echo "🔨 Building CDK template..."
          # Use npx to ensure we use the local typescript
          npx tsc
          echo "✅ CDK template built successfully"

      - name: Convert template to comma-separated format
        id: format-templates
        shell: bash
        run: |
          # Convert space-separated templates to comma-separated
          TEMPLATES_SPACE="${{ needs.detect-changes.outputs.templates }}"
          TEMPLATES_COMMA=$(echo "$TEMPLATES_SPACE" | tr ' ' ',' | sed 's/,*$//' | sed 's/^,*//')
          echo "templates-comma=$TEMPLATES_COMMA" >> $GITHUB_OUTPUT
          echo "📦 Templates to deploy (comma-separated): $TEMPLATES_COMMA"

      - name: Preview infrastructure changes
        working-directory: infra
        shell: bash
        run: |
          echo "🔍 Previewing changes for templates: ${{ steps.format-templates.outputs.templates-comma }}"
          ACCOUNT_ID="${{ steps.check-bootstrap.outputs.account-id }}"
          CDK_DEFAULT_ACCOUNT=$ACCOUNT_ID CDK_DEFAULT_REGION=us-east-1 \
          npx cdk diff --all \
            --context "templates=${{ steps.format-templates.outputs.templates-comma }}" || true

      - name: Deploy infrastructure
        working-directory: infra
        shell: bash
        run: |
          echo "🚀 Deploying infrastructure for templates: ${{ steps.format-templates.outputs.templates-comma }}"
          ACCOUNT_ID="${{ steps.check-bootstrap.outputs.account-id }}"
          
          # Deploy all stacks at once with comma-separated templates
          CDK_DEFAULT_ACCOUNT=$ACCOUNT_ID CDK_DEFAULT_REGION=us-east-1 \
          npx cdk deploy --all \
            --context "templates=${{ steps.format-templates.outputs.templates-comma }}" \
            --require-approval never \
            --verbose
          
          echo "✅ Successfully deployed infrastructure for all templates"

      - name: Build templates
        shell: bash
        run: |
          echo "🔨 Building templates..."
          IFS=' ' read -ra TEMP_ARR <<< "${{ needs.detect-changes.outputs.templates }}"
          for template in "${TEMP_ARR[@]}"; do
            if [ -n "$template" ]; then
              echo "Building template: $template"
              if [ -d "templates/$template" ]; then
                TEMPLATE=$template npx vite build
                echo "✅ Built $template"
              else
                echo "⚠️ Template directory templates/$template not found"
              fi
            fi
          done

      - name: Sync built sites to S3
        shell: bash
        run: |
          echo "📤 Syncing built sites to S3..."
          IFS=' ' read -ra TEMP_ARR <<< "${{ needs.detect-changes.outputs.templates }}"
          for template in "${TEMP_ARR[@]}"; do
            if [ -n "$template" ]; then
              echo "Syncing $template to S3..."
              
              if [ -d "templates/$template/dist" ]; then
                # Sync to the fixed bucket with template path
                _template=$(echo "$template" | tr '[:upper:]' '[:lower:]')

                if [ -d "templates/$template/dist" ]; then
                    aws s3 sync "templates/$template/dist" "s3://$S3_BUCKET/templates/$_template" \
                      --delete \
                      --region eu-south-2 \
                      --exclude ".*"
                    
                    echo "✅ Synced $template to s3://$S3_BUCKET/$_template"
                else
                    echo "⚠️ Build directory templates/$template/dist not found for $template"
                fi
            fi
          done

      - name: Invalidate CloudFront caches
        shell: bash
        run: |
          echo "🔄 Invalidating CloudFront caches for updated templates..."
          IFS=' ' read -ra TEMP_ARR <<< "${{ needs.detect-changes.outputs.templates }}"
          
          for template in "${TEMP_ARR[@]}"; do
            if [ -n "$template" ]; then
              # Lowercase version for AWS resources
              _template=$(echo "$template" | tr '[:upper:]' '[:lower:]')

              echo "Invalidating cache for: $template"
              

              STACK_EXISTS=$(aws cloudformation describe-stacks \
                --region us-east-1 \
                --stack-name "Site-$_template" \
                --query "Stacks[0].StackName" \
                --output text 2>/dev/null || echo "")

              if [ -z "$STACK_EXISTS" ]; then
                echo "⚠️ Stack Site-$_template not found, skipping cache invalidation"
                continue
              fi

              # Get distribution ID from stack outputs
              DISTRIBUTION_ID=$(aws cloudformation describe-stacks \
                --region us-east-1 \
                --stack-name "Site-$_template" \
                --query 'Stacks[0].Outputs[?OutputKey==`'$_template'DistributionId`].OutputValue' \
                --output text 2>/dev/null)
              
              if [ -n "$DISTRIBUTION_ID" ] && [ "$DISTRIBUTION_ID" != "None" ]; then
                echo "Creating invalidation for distribution: $DISTRIBUTION_ID"
                aws cloudfront create-invalidation \
                  --distribution-id "$DISTRIBUTION_ID" \
                  --paths "/*" \
                  --output table
                echo "✅ Cache invalidated for $template"
              else
                echo "⚠️ No distribution ID found for $template"
              fi
            fi
          done

      - name: Deployment Summary
        shell: bash
        run: |
          echo "🎉 Deployment Summary"
          echo "===================="
          echo "Deployed templates: ${{ needs.detect-changes.outputs.templates }}"
          echo "Total templates: $(echo '${{ needs.detect-changes.outputs.templates }}' | wc -w)"
          echo ""
          echo "🌐 Access your sites at:"
          IFS=' ' read -ra TEMP_ARR <<< "${{ needs.detect-changes.outputs.templates }}"
          for template in "${TEMP_ARR[@]}"; do
            if [ -n "$template" ]; then
              echo "  • https://$template.e-info.click"
            fi
          done
          echo ""
          echo "📊 S3 bucket: $S3_BUCKET"
          echo "🌍 Certificate region: us-east-1"
          echo "🗂️ S3 region: eu-south-2"
